# Specify the docker image to use (only used if using docker runners)
# See: http://doc.gitlab.com/ee/ci/docker/using_docker_images.html
image: ubuntu:20.04

# Define commands that run before each job's script
before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update
  - apt-get install -y gcc g++ cmake lcov autoconf libtool git python3 curl
  - git clone --depth=1 https://github.com/spack/spack.git
  - sed -i 's#"${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH}"#"${PACKAGE}"#g' spack/etc/spack/defaults/config.yaml
  - . ./spack/share/spack/setup-env.sh
  - spack external find cmake
  - spack install kokkos+openmp

stages:
  - build
  - test
  - deploy

buildCoverage:
  stage: build
  script:
    - mkdir -p buildCoverage
    - cd buildCoverage/
    - cmake .. -DWITH_CODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=../spack/opt/spack/kokkos -DENABLE_KMDS=true
    - make
  artifacts:
    paths:
    - buildCoverage
    expire_in: 30 days
    
buildRelease:
  stage: build
  script:
    - mkdir -p buildRelease
    - cd buildRelease/
    - cmake .. -DWITH_TEST=ON -DCMAKE_BUILD_TYPE=Release
    - make
  artifacts:
    paths:
    - buildRelease
    expire_in: 30 days

testCoverage:
  stage: test
  script:
    - cd buildCoverage/
    - make code_cover_gmds
 
testRelease:
  stage: test
  script:
    - cd buildRelease/
    - make test
    
deployRelease:
  stage: deploy
  script:
    - cd buildRelease/
    - make install
